spring:
  application:
    name: redis-cluster
  redis:
    cluster:
      nodes: server.ip:7001,server.ip:7002,server.ip:7003,server.ip:7004,server.ip:7005,server.ip:7006
      max-redirects:   # 集群中最大重定向次数不使用则可以不配置
redis:
  timeout: 2000 # 客户端超时时间单位是毫秒 默认是2000
  maxIdle: 10 # 最大空闲数
  maxTotal: 50 # 控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxWaitMillis: 1000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis: 300000 # 连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun: 3 # 每次释放连接的最大数目,默认3
  timeBetweenEvictionRunsMillis: 30000 # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow: true # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testWhileIdle: true # 在空闲时检查有效性, 默认false
  password: whaty!@#123
  database: 0