spring:
  redis:
    database: 0
    host: server.ip
    port: 6379
    password: whaty!@#123
    timeout: 1000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
